name: CI - build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Vitest tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Build the project
        run: npm run cibuild --if-present
        env:
          CI: true

      - name: Define 404 html
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
